server:
  port: 8001

spring:
  application:
    name: provider
eureka:
  instance: # eureka 的主机名字
    instance-id: provider-8001
    # 悬浮显示 ip
    prefer-ip-address: true
  client:
    # true 表示向注册中心注册自己
    register-with-eureka: true
    # true 表示向 EurekaServer 拉取自己的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka